FIX(pandas): 0.25.1 broke INDEXED comparisons ...
where expressions like:
    col == col.shirt()
raised:
    TypeError: Index(...) must be called with a collection of some kind, `n` was passed